name: Test Workflow

on:
  release:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test One
      run: echo tag pushed [${{ github.event.push.ref }}]
