name: Test Workflow

on:
  release:
    types: [created]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test One
      run: echo tag pushed [${GITHUB_REF}]
